### ISSUE TITLE
Training with own data set

### ISSUE THREAD

**Issue by HamzahNizami** [chwilms/AttentionMask#4]
Hi there, i'm new to the computer vision scene, and was wondering if i could get more information on how to use you model. I am currently working on strawberry detection in fields, and with strawberry's being fairly small, your model caught my attention. I was wondering if this would be problem solvable by your model. I know issues should not be used like this, so is there anyway I can get in contact with you. 

Thanks in advance.

**Comment by chwilms** [comment]
Hi, @HamzahNizami I will add a brief description on how to change the dataset shortly. For getting in touch, follow the first link in the readme and you will be directed to our webpages, where you can find my email.

**Comment by HamzahNizami** [comment]
Okay thank you. A description on how to change the dataset would be perfect. Thanks in advance

**Comment by chwilms** [comment]
I will add it to the README file.

**Comment by chwilms** [comment]
I updated the README file.
