### ISSUE TITLE
GPU out of memory

### ISSUE THREAD

**Issue by HamzahNizami** [chwilms/AttentionMask#5]
Hi there, I successfully followed the instructions up until the "Inference stage". Here, I attempted to generate proposals for the COCO dataset by using the command provided in the READ.Me.  Upon doing so I got the following error:

loading annotations into memory...
Done (t=3.57s)
creating index...
index created!
Progress:  |--------------------------------------------------| 0.0% CompleteF0226 17:52:22.489114  3020 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)

I am currently running the following: 

- Ubuntu 18.04
- Open CV 3.2
- Python 2.7
- Cuda 9.0 (followed these instructions for installation https://gist.github.com/Mahedi-61/2a2f1579d4271717d421065168ce6a73) 
- GPU - GTX 1060 6GB

Any help would be appreciated, thanks in advance.

**Comment by chwilms** [comment]
Your GPU is too small. You can try follow the instructions in the README on reducing memory footprint, however, I highly doubt it will be enough to remove the scales 24, 48 and 96. You probably have to reduce the input image size. You can do this in the configs/myModel.config file by reducing SCALE for training or TEST_SCALE for testing. This will lead, however, to worse results than in the paper.

**Comment by HamzahNizami** [comment]
Any recommendations on what to reduce the number to?

**Comment by HamzahNizami** [comment]
I lowered both to 700, and got the following error even after 100% completetion 

Progress:  |██████████████████████████████████████████████████| 100.0% CompleteF0227 14:57:04.590605  8270 syncedmem.hpp:31] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by chwilms** [comment]
This error is normal, it is a Caffe problem and happens during clean up. Your results are correct

**Comment by HamzahNizami** [comment]
Right okay. I ran the evaluation command several times, and each time it seems to crash my computer (i.e. it freezes)?

**Comment by HamzahNizami** [comment]
python evalCOCO.py attentionMask-8-128 --dataset val2014 --useSegm True --end 5000
loading annotations into memory...
Done (t=4.03s)
creating index...
index created!
Loading and preparing results...
Killed


currently getting this error when it doesn't freeze

**Comment by HamzahNizami** [comment]
I am currently under the assumption that when running the evalCOCO.py, it causes immense resource starvation leading to the process either getting "Killed" or the computer freezing. After using the command I analyzed memory usage via the "System Monitor" and noticed that the computer freezes as the memory usage for python hits around 14gb. I am currently running the following specs (added below), and I am assuming that I may be running out of memory. I am currently thinking of assigning more swap memory, but currently unsure what to do. Any input would be appreciated and I was also wondering what hardware + software specs you used when running for the results in the paper. Thanks in advance.

![screenshot from 2019-02-28 09-22-51](https://user-images.githubusercontent.com/32271819/53555759-7941ad00-3b3a-11e9-81a4-a5ae44197454.png)

**Comment by chwilms** [comment]
Your are right, it's a problem of the CPU memory. It takes a lot of memory to load a json file with 1000 proposals for 5000 images. Therefore, you either have to cut down on the images by using --end in testing and evaluation (e.g. --end 1000 -> testing only the first 1000 images of the dataset) or cut down on the proposals by cutting down the number to 500 or 100. The later can be done by changing the ´dynamicK´  variable in ´utils.py´ line 90 to 500 or 100. Then you have to rerun testing and evaluation.

**Comment by HamzahNizami** [comment]
Right okay, thanks. I am currently trying to run the train.sh script with the default GitHub cloned repository. I am currently encountering the following runtime error:


*** Check failure stack trace: ***
./train.sh: line 26: 15023 Aborted                 (core dumped) python trainAttentionMask.py 0 attentionMask-8-128 --restore attentionMask-8-128_iter_$STEP_OLD.solverstate --step $SIZE_EPOCH
training done
start validation
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0228 17:59:53.975257 15040 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0228 17:59:53.975277 15040 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0228 17:59:53.975280 15040 _caffe.cpp:125] Net('models/attentionMask-8-128.test.prototxt', 1, weights='params/attentionMask-8-128_iter_880000.caffemodel')
Traceback (most recent call last):
  File "testAttentionMask.py", line 58, in <module>
    caffe.TEST)
RuntimeError: Could not open file params/attentionMask-8-128_iter_880000.caffemodel
validation done
start evaluation
Traceback (most recent call last):
  File "evalCOCO.py", line 42, in <module>
    cocoDt = cocoGt.loadRes("results/%s.json" % args.model)
  File "build/bdist.linux-x86_64/egg/pycocotools/coco.py", line 317, in loadRes
AssertionError: Results do not correspond to current coco set
evaluation done
